const defaultLayout = [
  {
    "bt-negative-color": "#ffffff",
    "bt-negative-color-hover": "#ee4a52",
    "bt-negative-text-color": "#000000",
    "bt-negative-text-color-hover": "#ffffff",
    "box-shadow": "0px 0px 6px -1px rgba(0, 0, 0, 0.31)",
    "bt-positive-color": "#292929",
    "bt-positive-color-hover": "#5a5a5a",
    "bt-positive-text-color": "#ffffff",
    "bt-positive-text-color-hover": "#ffffff",
    "bt-purchase-color": "#28a745",
    "bt-purchase-color-hover": "#00bf59",
    "bt-purchase-text-color": "#ffffff",
    "bt-purchase-text-color-hover": "#000000",
    "card-background": "#ffffff",
    "card-background-hover": "#ffffff",
    "card-color-details": "#000000",
    "card-color-details-hover": "#000000",
    "card-color-price": "#ce171f",
    "card-color-price-hover": "#ce171f",
    "default-color": "#ffff",
    "default-color-hover": "#e6dfda",
    "default-color-icons": "#ce171f",
    "notifications-icons-color": "#ffffff",
    "notifications-icons-bgcolor": "#292929",
    "icons-footer-mobile": "#ffffff",
    "explore-block-color": "#ffffff",
    "explore-block-color-hover": "#ce171f",
    "explore-block-text-color": "#000000",
    "explore-block-text-color-hover": "#ffffff",
    "font-color": "#000000",
    "font-color-hover": "#292929",
    "footer-background-color": "#85a9cd",
    "footer-text-color": "#000000",
    "footer-text-color-hover": "#292929",
    "footer-title-color": "#000000",
    "header-color": "#ffffff",
    "header-font-color": "#292929",
    "header-secondary-color": "#cc201f",
    "header-secondary-font-color": "#ffffff",
    "logo-img": "/images/logo.svg",
    "negative-button-border": "transparent",
    "profile-card-color": "#ffffff",
    "profile-card-color-hover": "#ffffff",
    "title-color": "#292929",
    "title-modal-color": "#ffffff",
    "menu-sandwich-body": "#231f20",
    "menu-sandwich-header": "#231f20",
    "menu-sandwich-color": "#ffffff",
    "menu-sandwich-color-secondary": "#ffffff",
    "input-border-color": "#dddddd",
    "input-border-color-hover": "#ce171f",
    "configurable-attributes-color": "#000000",
    "configurable-attributes-color-hover": "#000000",
    "configurable-attributes-bgcolor": "#ffffff",
    "configurable-attributes-bgcolor-hover": "#f8dcde",
    "configurable-attributes-border": "",
    "configurable-attributes-border-hover": "#ce171f",
    "card-hover-transform-scale": "scale(1.025)",
    "card-hover-box-shadow": "0.5px 0.5px 4px 0px rgba(153, 153, 153, 1)",
    "bt-border-radius": "10px",
    "stamp-percentage-discount": "#f8aa24",
    "payment-method-card": "#F1F2F2",
    "am-i-professional": "",
  },
];
export default defaultLayout;
